import React from "react";
import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout({ title, children }) {
    
    return (
        <>
            <Head>
                <title>{title ? title + '- afif chow' : 'afif chow'}</title>
                <meta name="description" content="Generated by create next app" />
                <link href="/dist/output.css" rel="stylesheet"></link>
                <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
            </Head>
            <div className = "flex min-h-screen flex-col justify-between">
            <header>
                <Navbar/>
            </header>
            <main>
                {children}
            </main>
            <footer className="flex justify-center h-14 shadow-inner">
                @copyright sunmi-TH
            </footer>
        </div>
        </>
    )
}