import React from "react";
import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout({ title, children }) {
    
    return (
        <>
            <Head>
                <title>{title ? title + '- afif chow' : 'afif chow'}</title>
                <meta name="description" content="Generated by create next app" />
                <link href="/dist/output.css" rel="stylesheet"></link>
            </Head>
            <div className = "flex min-h-screen flex-col justify-between">
            <header>
                <Navbar/>
            </header>
            <main>
                {children}
            </main>
            <footer className="flex justify-center h-14 shadow-inner">
                @copyright sunmi-TH
            </footer>
        </div>
        </>
    )
}